import type { Group, Source, FeedItem } from './types';

export const GROUPS: Group[] = [
  { id: 'all',  name: 'all',         n: 1247 },
  { id: 'eng',  name: 'engineering', n: 412  },
  { id: 'ai',   name: 'ai/ml',       n: 286  },
  { id: 'sys',  name: 'systems',     n: 198  },
  { id: 'sec',  name: 'security',    n: 134  },
  { id: 'rust', name: 'rust',        n: 92   },
  { id: 'pers', name: 'personal',    n: 125  },
];

export const SOURCES: Source[] = [
  { id: 'hn-front',      kind: 'hn',     name: 'hn:front',         host: 'news.ycombinator.com',    items: 30,  unread: 14,  lastSync: '00:42', status: 'ok',    latencyMs: 188, group: 'all',  failureStreak: 0 },
  { id: 'hn-newest',     kind: 'hn',     name: 'hn:newest',        host: 'news.ycombinator.com',    items: 200, unread: 187, lastSync: '00:42', status: 'ok',    latencyMs: 211, group: 'all',  failureStreak: 0 },
  { id: 'r-rust',        kind: 'reddit', name: 'r/rust',           host: 'reddit.com',              items: 25,  unread: 9,   lastSync: '02:18', status: 'ok',    latencyMs: 312, group: 'rust', failureStreak: 0 },
  { id: 'r-programming', kind: 'reddit', name: 'r/programming',    host: 'reddit.com',              items: 50,  unread: 32,  lastSync: '02:18', status: 'ok',    latencyMs: 298, group: 'eng',  failureStreak: 0 },
  { id: 'r-localllama',  kind: 'reddit', name: 'r/LocalLLaMA',     host: 'reddit.com',              items: 40,  unread: 28,  lastSync: '02:18', status: 'ok',    latencyMs: 287, group: 'ai',   failureStreak: 0 },
  { id: 'r-machine',     kind: 'reddit', name: 'r/MachineLearning', host: 'reddit.com',             items: 35,  unread: 19,  lastSync: '02:18', status: 'ok',    latencyMs: 304, group: 'ai',   failureStreak: 0 },
  { id: 'rss-lwn',       kind: 'rss',    name: 'LWN.net',          host: 'lwn.net/headlines/rss',   items: 12,  unread: 4,   lastSync: '04:11', status: 'ok',    latencyMs: 142, group: 'sys',  failureStreak: 0 },
  { id: 'rss-acolyer',   kind: 'rss',    name: 'the morning paper', host: 'blog.acolyer.org/feed',  items: 8,   unread: 2,   lastSync: '04:11', status: 'stale', latencyMs: 0,   group: 'sys',  failureStreak: 1 },
  { id: 'rss-fasterthn', kind: 'rss',    name: 'fasterthanli.me',  host: 'fasterthanli.me/atom.xml', items: 6,  unread: 1,   lastSync: '04:11', status: 'ok',    latencyMs: 96,  group: 'rust', failureStreak: 0 },
  { id: 'rss-julia',     kind: 'rss',    name: 'Julia Evans',      host: 'jvns.ca/atom.xml',        items: 9,   unread: 3,   lastSync: '04:11', status: 'ok',    latencyMs: 87,  group: 'eng',  failureStreak: 0 },
  { id: 'rss-krebs',     kind: 'rss',    name: 'Krebs on Security', host: 'krebsonsecurity.com/feed',items: 7,  unread: 2,   lastSync: '04:11', status: 'ok',    latencyMs: 156, group: 'sec',  failureStreak: 0 },
  { id: 'rss-pdo',       kind: 'rss',    name: 'Phoronix',         host: 'phoronix.com/rss.php',    items: 22,  unread: 11,  lastSync: '04:11', status: 'error', latencyMs: 0,   group: 'sys',  failureStreak: 4 },
];

export const ITEMS: FeedItem[] = [
  { id: 'i01', src: 'hn-front',      kind: 'link',      domain: 'github.com',           thumb: { h: 200, label: 'gh'   }, title: 'Show HN: I built a local-first feed reader for power users with Tauri+Svelte',                                                 author: 'tgrn',          age: '12m', score: 284,  n: 96,  tags: ['release','technical'],               aiScore: 0.92, read: false, saved: true,  body: 'After months of iterating on a Bloomberg-density reader for Android I finally have something usable...' },
  { id: 'i02', src: 'r-rust',        kind: 'text',                                                                         title: 'Async cancellation: a practical guide to AbortHandle, JoinSet, and structured concurrency',                                      author: 'tower-rs',      age: '38m', score: 412,  n: 71,  tags: ['technical','tutorial','deepdive'],    aiScore: 0.88, read: false, saved: false, body: 'Cancellation in async Rust is not as simple as dropping a future. There are at least four overlapping mechanisms worth understanding...', snippet: 'tldr; there are four overlapping mechanisms and dropping the future is the worst one. structured concurrency wins.' },
  { id: 'i03', src: 'rss-lwn',       kind: 'link',      domain: 'lwn.net',              thumb: { h: 30,  label: 'LWN'  }, title: 'Per-CPU page lists, MIGRATE_HIGHATOMIC, and the long road to defragmentation',                                                  author: 'corbet',        age: '1h',  score: 0,    n: 0,   tags: ['technical','research','deepdive'],    aiScore: 0.97, read: false, saved: true,  body: 'Memory compaction in the Linux kernel has come a long way since the era of unmovable pages...' },
  { id: 'i04', src: 'r-localllama',  kind: 'image',                                     thumb: { h: 280, label: 'chart'}, title: 'Llama-4-8B-Distill: ~3.2 tok/s on Pixel 9 Pro w/ NNAPI delegate',                                                             author: 'u/jhasse',      age: '1h',  score: 1820, n: 213, tags: ['ai/ml','technical','release'],        aiScore: 0.86, read: false, saved: false, body: 'Benchmarks across 7 phones. Quant int4. Speculative decoding off. Includes a script for repro...' },
  { id: 'i05', src: 'hn-newest',     kind: 'link',      domain: 'anon991.substack.com', thumb: { h: 0,   label: 'sub'  }, title: 'Why I left Vercel after 14 months',                                                                                           author: 'anon991',       age: '2h',  score: 38,   n: 142, tags: ['ragebait','low-effort'],              aiScore: 0.21, read: true,  saved: false, body: 'I joined Vercel in late 2024 expecting...' },
  { id: 'i06', src: 'rss-julia',     kind: 'link',      domain: 'jvns.ca',              thumb: { h: 320, label: 'jv'   }, title: 'How I debug DNS issues with dig +trace and nothing else',                                                                     author: 'b0rk',          age: '2h',  score: 0,    n: 0,   tags: ['tutorial','technical'],               aiScore: 0.91, read: false, saved: true,  body: 'When DNS breaks, dig is your best friend...' },
  { id: 'i07', src: 'r-machine',     kind: 'text',                                                                         title: '[D] Has anyone actually replicated the speculative-decoding numbers from the paper?',                                            author: 'u/grad42',      age: '3h',  score: 89,   n: 47,  tags: ['research','ai/ml'],                  aiScore: 0.78, read: false, saved: false, body: 'I ran the public eval harness three times...', snippet: 'I ran the public eval harness three times across two A100s. Best I got was 1.8x, not the 2.6x they claim. Anyone seeing matching numbers?' },
  { id: 'i08', src: 'hn-front',      kind: 'link',      domain: 'openbsd.org',          thumb: { h: 50,  label: 'BSD'  }, title: 'OpenBSD 7.6 released',                                                                                                        author: 'theo',          age: '3h',  score: 1024, n: 188, tags: ['news','release','technical'],         aiScore: 0.84, read: true,  saved: false, body: 'Theo de Raadt has announced the release of OpenBSD 7.6...' },
  { id: 'i09', src: 'r-programming', kind: 'video',     dur: '27:04',                   thumb: { h: 340, label: 'play' }, title: 'The history of the lambda calculus, explained with cats',                                                                     author: 'u/mosh',        age: '4h',  score: 412,  n: 38,  tags: ['tutorial','meme'],                   aiScore: 0.58, read: false, saved: false, body: 'A surprisingly approachable intro...' },
  { id: 'i10', src: 'rss-krebs',     kind: 'link',      domain: 'krebsonsecurity.com',  thumb: { h: 10,  label: 'KoS'  }, title: 'Phishing-as-a-Service kit "RockStorm" found targeting auth flows of 1Password, Bitwarden',                                   author: 'krebs',         age: '5h',  score: 0,    n: 0,   tags: ['news','technical'],                   aiScore: 0.93, read: false, saved: false, body: 'A new phishing kit observed in the wild...' },
  { id: 'i11', src: 'r-rust',        kind: 'text',                                                                         title: 'Cargo: opt-level=3 + LTO=fat actually slowed my binary down — what?',                                                        author: 'u/perfdude',    age: '6h',  score: 76,   n: 31,  tags: ['technical','research'],               aiScore: 0.79, read: false, saved: false, body: 'I expected LTO=fat to be a no-brainer...', snippet: 'expected LTO=fat to be a no-brainer. binary got 12% slower on the workload that mattered. perf shows icache misses up 3x. theories welcome.' },
  { id: 'i12', src: 'rss-fasterthn', kind: 'link',      domain: 'fasterthanli.me',      thumb: { h: 220, label: 'ftl'  }, title: 'A half-hour to learn Tokio internals: runtimes, schedulers, parking',                                                        author: 'fasterthanlime', age: '7h', score: 0,    n: 0,   tags: ['tutorial','technical','deepdive'],    aiScore: 0.94, read: false, saved: true,  body: 'Tokio is the default async runtime in Rust...' },
  { id: 'i13', src: 'hn-front',      kind: 'image',                                     thumb: { h: 130, label: 'img'  }, title: 'New Apple Silicon chip rumored to outperform [screenshot.png]',                                                               author: 'leak1',         age: '8h',  score: 31,   n: 244, tags: ['screenshot','clickbait','low-effort'], aiScore: 0.18, read: true,  saved: false, body: 'A leaked benchmark...' },
  { id: 'i14', src: 'r-localllama',  kind: 'crosspost', crossFrom: 'r/MachineLearning', domain: 'huggingface.co',         thumb: { h: 50, label: 'HF' },  title: 'Phi-4-mini fine-tuned on stack overflow Q/A — release + weights',                             author: 'u/cmd',         age: '9h',  score: 318,  n: 64,  tags: ['ai/ml','release'],                   aiScore: 0.87, read: false, saved: false, body: 'A small but well-curated fine-tune...' },
  { id: 'i15', src: 'r-programming', kind: 'text',                                                                         title: '"Functional programming is dead, says man who hasn’t used FP since 2009"',                                               author: 'u/snark',       age: '10h', score: 8,    n: 412, tags: ['meme','ragebait'],                   aiScore: 0.12, read: true,  saved: false, body: '...', snippet: 'this is satire right?' },
  { id: 'i16', src: 'rss-pdo',       kind: 'link',      domain: 'phoronix.com',         thumb: { h: 280, label: 'ph'   }, title: 'Linux 6.13-rc4 brings amdgpu, btrfs, sched_ext fixes; new Intel Xe2 perf numbers',                                           author: 'phoronix',      age: '12h', score: 0,    n: 0,   tags: ['news','technical'],                   aiScore: 0.81, read: false, saved: false, body: 'The fourth release candidate of Linux 6.13 has been tagged...' },
  { id: 'i17', src: 'hn-newest',     kind: 'link',      domain: 'blog.cloudflare.com',  thumb: { h: 30,  label: 'cf'   }, title: 'A note on RocksDB latency tail when WAL is on cgroup-throttled disk',                                                        author: 'mlfew',         age: '14h', score: 142,  n: 28,  tags: ['research','technical','deepdive'],    aiScore: 0.95, read: false, saved: true,  body: 'We hit a p99.9 cliff in production...' },
  { id: 'i18', src: 'r-rust',        kind: 'text',                                                                         title: 'I rewrote my Python OCR pipeline in Rust. It went badly.',                                                                    author: 'u/anon',        age: '16h', score: 56,   n: 88,  tags: ['tutorial','technical'],               aiScore: 0.62, read: false, saved: false, body: 'A cautionary tale...', snippet: 'spent 6 weeks. ended up 2.4x slower than the original numpy+PIL version. lessons inside — this is not a "rewrite in rust" success story.' },
  { id: 'i19', src: 'rss-acolyer',   kind: 'link',      domain: 'blog.acolyer.org',     thumb: { h: 200, label: 'tmp'  }, title: 'Paper: "Building a fast, indexed key-value store for SSDs" (FAST ’24)',                                                 author: 'acolyer',       age: '18h', score: 0,    n: 0,   tags: ['research','deepdive'],                aiScore: 0.96, read: false, saved: false, body: 'A summary of the FAST ’24 best paper...' },
  { id: 'i20', src: 'r-machine',     kind: 'link',      domain: 'deepmind.google',      thumb: { h: 240, label: 'dm'   }, title: '[N] DeepMind announces something — link to 6-paragraph announcement post',                                                   author: 'u/news',        age: '1d',  score: 4,    n: 92,  tags: ['news','low-effort','clickbait'],      aiScore: 0.19, read: true,  saved: false, body: '...' },
];
